- pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
- pkg/apis/gcpprovider/v1beta1/register.go
- pkg/apis/gcpprovider/v1beta1/register_test.go
- pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
- pkg/cloud/gcp/actuators/machine/actuator.go
- pkg/cloud/gcp/actuators/machine/machine_scope.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
- pkg/cloud/gcp/actuators/services/compute/computeservice.go
- pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
- Add status API types
- Create proper struct type <-> rawExtension methods and tests for providerSpec and providerStatus
- Add providerID and providerStatus to machine scope and use new struct type <-> rawExtension methods
- Add reconcileMachineWithCloudState() to be called on Create for now
> Manage status

- pkg/cloud/gcp/actuators/machine/actuator.go
- pkg/cloud/gcp/actuators/machine/machine_scope.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
Existing machine:
```
I0510 11:18:11.794616   54428 controller.go:129] Reconciling Machine "agl060519-rnvnt-test-gcp-22"
I0510 11:18:11.794643   54428 controller.go:292] Machine "agl060519-rnvnt-test-gcp-22" in namespace "test-gcp" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0510 11:18:11.794657   54428 actuator.go:52] Checking if machine "agl060519-rnvnt-test-gcp-22" exists
I0510 11:18:12.614139   54428 reconciler.go:217] Machine "agl060519-rnvnt-test-gcp-22" already exists
I0510 11:18:12.614178   54428 controller.go:237] Reconciling machine "agl060519-rnvnt-test-gcp-22" triggers idempotent update
I0510 11:18:12.614224   54428 actuator.go:65] Updating machine "agl060519-rnvnt-test-gcp-22"
I0510 11:18:12.614843   54428 reconciler.go:135] Reconciling machine …
```
> Implement update

- Makefile
Instead of:
-ldflags "-X github.com/openshift/cluster-api-provider-gcp/pkg/version.Raw=36ecc64 -extldflags "-static""
we get:
-ldflags "-X github.com/openshift/cluster-api-provider-gcp/pkg/version.Raw=36ecc64 -extldflags -static"
And, instead of:
-ldflags '-extldflags "-static"'
we get:
-ldflags '-extldflags -static'
> Makefile: drop nested quoting

- pkg/cloud/gcp/actuators/machine/reconciler.go
This mimics aws behaviour for async creation by relying on the `instance.Status`.
Staging:
```
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"machine.openshift.io/v1beta1","kind":"Machine","metadata":{"annotations":{},"labels":{"machine.openshift.io/cluster-api-cluster":"agl060519-rnvnt","machine.openshift.io/cluster-api-machine-role":"test-gcp","machine.openshift.io/cluster-api-machine-type":"test-gcp"},"name":"agl060519-rnvnt-test-gcp-34","namespace":"test-gcp"},"spec":{"providerSpec":{"value":{"apiVersion":"gcpproviderconfig.openshift.io/v1beta1","canIPForward":true,"credentialsSecret":{"name":"test"},"deletionProtection":false,"disks":[{"autoDelete":true,"boot":true,"image":"projects/coreo …
```
> Convert create into async

- pkg/cloud/gcp/actuators/machine/reconciler.go
This inverts the behaviour of reconciler.exists() to only consider the
TERMINATED state when determining if the instance exists, or not.
> reconciler: change exists to consider TERMINATED state only

- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
- pkg/cloud/gcp/actuators/services/compute/computeservice.go
- pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Testing is minimal and would need further rework which can be done as
a follow-up PR.
> Make delete async

- Makefile
- hack/e2e.sh
This commit adds e2e test to Makefile.  This test
will clone cluster-api-actuator-pkg and run tests
from that clone.
> Add e2e make test

- pkg/cloud/gcp/actuators/machine/actuator.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
This commit adds machine.Name to most logging
to enable easier troubleshooting of logs with
grep.
> Prepend machine.Name to logging

- cmd/manager/main.go
The machine operator expects the controller to take a namespace flag:
https://github.com/openshift/machine-api-operator/blob/281f67cf0dd15c479f2f0f6046c53ccd3e73ba9b/pkg/operator/sync.go#L189
> Add namespace flag to controller command

- pkg/cloud/gcp/actuators/machine/machine_scope.go
With https://github.com/openshift/cloud-credential-operator/pull/92, the credential key used by the cloud creds operator will be `service_account.json`
> Fix name of the credentials key

- pkg/cloud/gcp/actuators/machine/reconciler.go
The user data that is passed to the GCP api does not need to be base64-encoded
> Do not b64-encode user data

- pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
Currently a public IP is generated for every network interface in a machine (by specifying a non-empty AccessConfig). This PR introduces a boolean to allow you to specify whether a public IP is needed. For OCP use cases it's not.
> Allow specifying whether you want a public IP

- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/services/compute/computeservice.go
- pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
The image parameter must be in the form:
https://www.googleapis.com/compute/v1/projects/{project}/global/images/{image}
> Pass full URL to image when creating compute instance

- pkg/cloud/gcp/actuators/machine/reconciler.go
Instead of introducing a different key for the alternate internal DNS,
simply use the same key that is already part of the core API. The CSR
approver will use either address to approve a machine request.
> Use the same type for both internal addresses

- pkg/cloud/gcp/actuators/machine/actuator.go
- pkg/cloud/gcp/actuators/machine/machine_scope.go
This changes the signature of Close() to return an error. The callers
of this function were happening in a defer block - those blocks have
been removed and we now return any error to the caller.
> Return errors from scope.Close()

- pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
- pkg/cloud/gcp/actuators/machine/machine_scope.go
The project associated with a particular GCP credential key may not be the same project that was specified for the cluster install. The service account associated with the credential key may exist in one project and manage a cluster in a different project. Adding a project ID to the machine provider spec ensures that the machine controller uses the intended project in the edge case where it's different than the project associated with the credential key.
If projectID is not specified on machine, use the one from the credential secret.
> Add project ID to machine provider spec

- README.md
- pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
- pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
- pkg/cloud/gcp/actuators/services/compute/computeservice.go
- pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
This commit extends the providerSpec to add the field
TargetPools, which is a list of strings specifying
targetpools you wish to add the instance to.
This commit supports removing the instance from a
target pool when the machine-object is deleted.
This commit also adds unit tests.
The target pools must already exist for this to work, similiar to AWS LB's.
If we don't have this PR, masters won't be added to the appropriate LB's when doing disaster recovery.
> Add support for TargetPools

- pkg/cloud/gcp/actuators/machine/reconciler.go
Set common machine fields so when a machine provisioned in Azure is listed through oc get machines
all additional printer colums are properly populated. E.g. region, zone, instance type.
```
NAME                     STATE     TYPE            REGION  	 ZONE            AGE
jchalo-pm2hk-m-0         RUNNING   n1-standard-4   us-central1   us-central1-a   20h
jchalo-pm2hk-m-1         RUNNING   n1-standard-4   us-central1   us-central1-b   20h
jchalo-pm2hk-m-2         RUNNING   n1-standard-4   us-central1   us-central1-c   20h
jchalo-pm2hk-w-a-wfrmf   RUNNING   n1-standard-4   us-central1   us-central1-a   20h
jchalo-pm2hk-w-b-l2wv5   RUNNING   n1-standard-4   us-central1   us-central1-b   20h
jchalo-pm2hk-w-c-fvh4h   RUNNING   n1-standard-4   us-central1   us-central1-c   20h
```
> bug 1740004: Set additional machine annotations/labels to get pretty machine output

- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
So the installer can potentially delete all gcp instances when a cluster is destroyed.
Label key constraints: The key must start with a lowercase character,
can only contain lowercase letters, numeric characters, underscores and dashes.
The key can be at most 63 characters long. International characters are allowed.
Thus, using "kubernetes-io-cluster-CLUSTERID=owned" form instead.
```
$ gcloud compute instances list --format='table(name,status,labels.list())' | grep jchalo-cf757
jchalo-cf757-m-0                        RUNNING
jchalo-cf757-w-a-jwddf                  RUNNING
jchalo-cf757-m-1                        RUNNING
jchalo-cf757-w-b-92xt6                  RUNNING  kubernetes-io-cluster-jchalo-cf757=owned
jchalo-cf757-w-b-wd8nm                  RUNNING
jchalo-cf757-m-2 …
```
> Label instances created by the actuator with cluster ID

- pkg/cloud/gcp/actuators/machine/machine_scope.go
The machine status needs to be updated first since the next call to
storeMachineSpec updates entire machine object. If done in the reverse
order, the machine status could be updated without setting the
LastUpdated field in the machine status.
This is the same change[1] that has been applied to the Azure actuator.
[1] - https://github.com/openshift/cluster-api-provider-azure/pull/76
> machine/machine_scope: update status first in Close()

- Dockerfile
This avoids actual static linking of -lpthread,-lc,etc. on some architectures.
This reopens https://github.com/openshift/cluster-api-provider-gcp/pull/38.
> Fix linking on other architectures

- pkg/cloud/gcp/actuators/machine/reconciler.go
In GCP an instance in 'terminated' state means it has been stopped and can be restarted. Therefore the machine API considers that instance to exists https://cloud.google.com/compute/docs/instances/instance-life-cycle
> bug 1771919: Consider an instance to exist regardless the status

- go.mod
- go.sum
- vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
- vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
- vendor/modules.txt
Revendor mao with timeout formatting fix https://github.com/openshift/machine-api-operator/pull/495
> Revendor mao with timeout formatting fix

- Makefile
- hack/ci-test.sh
**What this PR does / why we need it**:
This PR restores the original behaviour of `make unit`, depends on https://github.com/openshift/release/pull/7755 being merged first
> Restore original make unit behaviour

- Dockerfile
- Makefile
- go.mod
- hack/go-fmt.sh
- hack/go-vet.sh
- hack/goimports.sh
- hack/gosec.sh
Bump all scripts/docker images to Go 1.13
> [OCPCLOUD-813] Bump scripts to Go 1.13

- pkg/cloud/gcp/actuators/machine/reconciler.go
GCP platform provides search paths to resolve the virtual machine names by default. see https://cloud.google.com/compute/docs/internal-dns#resolv.conf
this also allows nodes in clusters to have node-names matching the virtual machine name instead of the fqdn be because fqdn is too long for RHCOS to accept as hostname
by default
> Bug 1809345: Add the machine's name as a known NodeInternalDNS

- Dockerfile
- Makefile
- cmd/termination-handler/main.go
- config/crds/machine.openshift.io.crd.yaml
- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/termination/termination.go
- pkg/termination/termination_suite_test.go
- pkg/termination/termination_test.go
This PR adds a termination handler for spot instances. It is based on the termination handler that Joel wrote for AWS and has similar logic.
Based on [documentation](https://cloud.google.com/compute/docs/instances/preemptible), spot instances run on GCP for 24 hours, but under some conditions, they might be terminated earlier so polling logic inherited from AWS should be the best option here.
This implementation of the termination handler is simpler than https://github.com/GoogleCloudPlatform/k8s-node-termination-handler, made specifically for machine API, and leverages its ability for draining nodes.
https://cloud.google.com/compute/docs/instances/preemptible
https://github.com/openshift/cluster-api-provider-aws/pull/308
https://cloud.google.com/compute/docs/instances/create-start-preempt …
> Add termination handler for spot instances

- cmd/manager/main.go
Couple of new cli arguments for configuring leader election:
```
-leader-elect
Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability. (default true)
-leader-elect-lease-duration int
The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate. This is only applicable if leader election is enabled. (default 15s)
-leader-elect-resource-namespace string
The namespace of resource object that is used for locking during leader election. If unspecified, the controller watches for …
```
> [OCPCLOUD-492] Implement leader election for gcp provider

- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
- pkg/termination/termination.go
Add spot instance label to machine spec, we need this label to be passed to the node.
> Add spot instance label to machine spec

- pkg/cloud/gcp/actuators/machine/reconciler.go
Based on the api reference for [compute.instance.insert][0]
```
disks[].initializeParams.sourceImage:
The source image to create this disk. When creating a new instance, one of initializeParams.sourceImage or initializeParams.sourceSnapshot or disks.source is required except for local SSD.
To create a disk with one of the public operating system images, specify the image by its family name. For example, specify family/debian-9 to use the latest Debian 9 image:
projects/debian-cloud/global/images/family/debian-9
Alternatively, use a specific version of a public operating system image:
projects/debian-cloud/global/images/debian-9-stretch-vYYYYMMDD
To create a disk with a custom image that you created, specify the image name in the following format:
global/images/my-custom-image
You can also …
```
> support sourceImage outside the existing project

- pkg/termination/termination.go
- pkg/termination/termination_suite_test.go
- pkg/termination/termination_test.go
This ensures that we are passing the scheme we are adding the machine api to, into the client. It also fixes the scheme import so that we use the standard client-go scheme instead of the kubectl scheme
> BUG 1856597: Pass scheme to client creation so that it uses scheme with Machine API

- cmd/manager/main.go
- pkg/cloud/gcp/actuators/machine/actuator.go
- pkg/cloud/gcp/actuators/machine/actuator_test.go
- pkg/cloud/gcp/actuators/machine/machine_scope.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machineset/controller.go
- pkg/cloud/gcp/actuators/services/compute/computeservice.go
- pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
This PR adds tests for actuator events, but this required couple of other changes.
1. Pass context to machine scope
2. Improve error formatting and make it consistent with other providers
3. Add GCP client builder, similar to what we have in AWS. This allows mocking the client in a cleaner way.
4. Validate machine labels in update()
https://github.com/openshift/machine-api-operator/blob/master/pkg/controller/vsphere/actuator_test.go
https://github.com/openshift/cluster-api-provider-aws/blob/master/pkg/actuators/machine/actuator_test.go
> Add tests for actuator events

- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
- pkg/cloud/gcp/actuators/machineset/controller_test.go
- pkg/cloud/gcp/actuators/util/gcp_credentials.go
This PR fixes couple minor linting issues
> Fix minor linting issues

- pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
- pkg/cloud/gcp/actuators/machine/reconciler.go
- pkg/cloud/gcp/actuators/machine/reconciler_test.go
This allows users to specify an alternative project for the network that the VM is created within. This allows for shared VPCs.
I have yet to test this in a real cluster, I want to verify this works before allowing it to merge, hence holding. This shouldn't block the review process though.
/hold
> BUG 1867262: Support networks shared from a different project

- go.mod
- go.sum
- vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
- vendor/modules.txt
Revendor MAO with timeout formatting fix
> Bug 1733474: Revendor MAO with timeout formatting fix

- Makefile
- hack/verify-diff.sh
Allowing automatic make generate checks in CI. It allows to keep track of API changes, client-generated code updates on each PR.
This PR is dependent on openshift/release#13400 to enable the functionality in CI.
> [OCPCLOUD-809] Add verify-diff check in generate task and enable in CI 

- pkg/termination/termination.go
- pkg/termination/termination_test.go
Switch from deleting the Machine to marking the Node with a Terminating condition.
This will integrate with an MHC to ensure that the Machine is deleted.
This should be possible using the Node's credentials and as such, the termination handler will not need its own credentials and extra permissions.
Requires openshift/machine-api-operator#627 before it will work
https://github.com/openshift/cluster-api-provider-aws/pull/332
> [OCPCLOUD-1044] Bug 1902157: Update termination handler to use node conditions

- pkg/cloud/gcp/actuators/machine/reconciler.go
To enable the termination handler MHC to work, we need to label the Machine as well as the Node as interruptible.
> Bug 1907286: Ensure Machine is marked interruptible as well as Node

- pkg/termination/termination.go
When creating an http request in go, this sets two goroutines in the background running. If the body is not closed properly, these goroutines are leaked. This leads to a gradual increase in memory used by the application over time. We must ensure we always close response bodies
> Bug 1934021: Ensure response body is closed when we are finished with the request

- pkg/cloud/gcp/actuators/machineset/cache.go
- pkg/cloud/gcp/actuators/machineset/controller.go
- pkg/cloud/gcp/actuators/machineset/controller_test.go
Prevent endless reconciles for machineSet due to failed attempt to set scale from zero annotation when the instance type is missing in our static list.
> Bug 1918910: Only log error on nonexistent instance type for scale from zero

- .gitignore
- Makefile
- README.md
- hack/go-fmt.sh
- hack/go-vet.sh
- hack/goimports.sh
- hack/gosec.sh
- hack/owner_reset.sh
Fixed broken Makefile targets.
Added script to fix permission issues.
Updated Readme.
Update .gitignore.
> [OCPCLOUD-1066] Makefile fix 

- Makefile
- hack/go-mod.sh
Add option to run make vendor in container like other targets, to avoid issues with go module caching depending on what you already have on your machine.
> add in-container vendor

- go.mod
- go.sum
- pkg/cloud/gcp/actuators/services/compute/computeservice.go
- vendor/golang.org/x/oauth2/authhandler/authhandler.go
- vendor/golang.org/x/oauth2/google/default.go
- vendor/golang.org/x/oauth2/google/doc.go
- vendor/golang.org/x/oauth2/google/google.go
- vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
- vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
- vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
- vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
- vendor/golang.org/x/oauth2/google/jwt.go
- vendor/modules.txt
Workload identity federation will enable short lived credentials in a gcp
cluster. Current version golang.org/x/oauth2 does not support it.
ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
docs: https://github.com/openshift/cloud-credential-operator/pull/376
> update golang.org/x/oauth2 to support gcp workload identity

- pkg/cloud/gcp/actuators/machine/reconciler.go
BasePath was changed in GCP sdk. In c6faa4bae2ca201573c628e92b112971833284e7 sdk was updated.
See ```git diff c6faa4bae2ca201573c628e92b112971833284e7~1..HEAD vendor/google.golang.org/api/compute/v1/compute-gen.go```
```
diff --git a/vendor/google.golang.org/api/compute/v1/compute-gen.go b/vendor/google.golang.org/api/compute/v1/compute-gen.go
index 2f65969c..03fecd97 100644
--- a/vendor/google.golang.org/api/compute/v1/compute-gen.go
+++ b/vendor/google.golang.org/api/compute/v1/compute-gen.go
@@ -1,4 +1,4 @@
-// Copyright 2020 Google LLC.
+// Copyright 2021 Google LLC.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
@@ -78,11 +78,12 @@ var _ = internaloption.WithDefaultEndpoint
const apiId = "compute:v1"
const apiName = "compute" …
```
> Bug 2009111: Fix broken path defaulting for disk image

- pkg/cloud/gcp/actuators/machineset/controller.go
- pkg/cloud/gcp/actuators/machineset/controller_test.go
Tested with `quay.io/elmiko/busybox` image with `limits: nvidia.com/gpu: 1` as workload for autoscaling tests.
> OCPCLOUD-1250: add annotation to enable gpu autoscaling

- openshift/e2e-tests.sh
This PR adds a script under `openshift/e2e-tests.sh` which can be invoked manually or through the OpenShift CI steps (as we already do for [unit tests](https://github.com/openshift/release/blob/ecf68889eb6507167b2a90d8daa95061b430efe2/ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml#LL44C1-L47C14)) to launch CAPI E2E tests from within the provider repo.
This mimics the [approach in the MAPI providers]( https://github.com/openshift/machine-api-provider-aws/blob/425a29de158582a931fd8052b306f4589ee90b61/hack/e2e.sh#L1C1-L10) where we clone the repo where the e2e tests reside and launch those from within the provider repo PRs.
> Add openshift/e2e-tests for CAPI E2E testing

- metadata.yaml
- test/e2e/config/gcp-ci.yaml
Temporarily carrying upstream fix (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1056) to metadata file until next patch release.
> OCPCLOUD-2218: UPSTREAM: 1056: fix: update metadata file to add the 1.5 releases

- openshift/Makefile
no-op change to trigger rebuild, following the issues at https://redhat-internal.slack.com/archives/CB95J6R4N/p1701163468934139
> OCPCLOUD-2256: No-op change to trigger image rebuild

- openshift/e2e-tests.sh
Fix e2e tests on release branches by running cluster-capi-operator tests off of the matching release branch.
> OCPBUGS-30586: fix e2e tests on release branches

- .snyk
we do not package or release anything from the test directory and it is safe to exclude from our snyk scans.
> OCPBUGS-28331: add test directory to snyk excludes

- openshift/manifests/0000_30_cluster-api_04_cm.infrastructure-gcp.yaml
- openshift/tools/go.mod
- openshift/tools/go.sum
- openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
- openshift/tools/vendor/modules.txt
In 4.17, we are enforcing this value for all OpenShift containers via tests, link in bug comment. This helps with debugging to ensure we have logs available.
Ref: https://github.com/openshift/cluster-capi-operator/pull/172
> OCPBUGS-33170: Container fallback to logs on error

- .gitignore
- vendor/github.com/emicklei/go-restful/v3/coverage.sh
- vendor/github.com/subosito/gotenv/.env
Image build was failing on Konflux due to missing go mod dependencies.
```
2025-04-04 17:30:06,588 ERROR vendor directory changed after vendoring:
A	vendor/github.com/emicklei/go-restful/v3/coverage.sh
A	vendor/github.com/subosito/gotenv/.env
2025-04-04 17:30:08,935 ERROR PackageRejected: The content of the vendor directory is not consistent with go.mod. Please check the logs for more details.
```
Konflux ignores .gitignore files since its a possible security gap.
> ART-12521: update go mod dependency for konflux

- openshift/infrastructure-components-openshift.yaml
- openshift/manifests/0000_30_cluster-api_04_cm.infrastructure-gcp.yaml
- openshift/tools/go.mod
- openshift/tools/go.sum
- openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
- openshift/tools/vendor/modules.txt
This PR updates manifests gen and then regenerates the manifests to pick up switch from v1beta1 to v1 for the admissionregistration group on the ValidatingAdmissionPolicy{Binding}s we use
> OCPBUGS-56962: [release-4.19] Update manifests to remove dependency on admissionregistration v1beta1
